### PR TITLE
Added LoadShM to load from shared memory into TVec, THash, TUNGraph, …

### PR DESCRIPTION
**Pull request by scoutsaachi**
…TNGraph, TNEANet, TTable, TTableContext, TMMNet, TUndirNet, TDirNet, TNodeNet, TNodeEDatNet, TNodeEdgeNet

Added TShMIn, a new instream that mmaps to a file in shared memory

### CODE REVIEW

**Comment by chantat** [comment]
Hi Saachi,

Another thing you have to be careful about is when the element is not word aligned. Suppose you have an element of size 5 bytes. The Save function would save element 1 to bytes 1 to 5 and element 2 to bytes 6 to 10. However, the in memory representation is likely to be padded where element 1 is bytes 1 to 5 + 3 byte padding and element 2 is bytes 9 to 13 + 3 byte padding. What we did was to make sure that pragma pack is always on for the element's class. This makes sure that the in memory representation is the same as the Save. Another approach would be to change the Save function such that it does the padding. Let me know if you have other approaches that might work better.

**Comment by roks** [comment]
That is a good point, thank you! Which are the top classes affected by padding?

**Comment by roks** [comment]
Thank you for your contribution, this code will be extremely useful.

**Comment by chantat** [comment]
Sorry for the slow reply. Mainly, whenever I have a custom TPair such as TPair<TInt, TChar> for example.

**Comment by roks** [comment]
I propose to implement the second option, Save() with padding, which will make the memory and disk representations the same. It is a generic solution. It might also be the fastest, but one would need to evaluate the tradeoff in speed between accessing packed structure vs larger structure.

**Pull request merged**
